//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGTY
    {
        public int IDCT { get; set; }
        public string Tendangnhap { get; set; }
        public string Matkhau { get; set; }
        public string Tencongty { get; set; }
        public string Diachi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
    }
}
