//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHDON
    {
        public string TenCT { get; set; }
        public string NguoiNop { get; set; }
        public string Vitri { get; set; }
        public string Mucluong { get; set; }
        public string Khuvuc { get; set; }
        public Nullable<System.DateTime> Thoihan { get; set; }
        public string Yeucau { get; set; }
        public int IDDon { get; set; }
    }
}
