//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOPDON
    {
        public int IDDon { get; set; }
        public Nullable<int> IDTT { get; set; }
        public string NguoiNop { get; set; }
        public string CongTy { get; set; }
        public Nullable<System.DateTime> NgayNop { get; set; }
        public string Vitri { get; set; }
        public Nullable<System.DateTime> Hanchot { get; set; }
        public string Yeucau { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string Gioithieubanthan { get; set; }
    }
}
